// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReVision;

namespace ReVision.Migrations
{
    [DbContext(typeof(RevisionContext))]
    partial class RevisionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("ReVision.Model.Proposition", b =>
                {
                    b.Property<int>("PropositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropositionTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QAModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropositionId");

                    b.HasIndex("QAModelId");

                    b.ToTable("Proposition");
                });

            modelBuilder.Entity("ReVision.Model.QAModel", b =>
                {
                    b.Property<int>("QAModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnswerPropositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QAModelId");

                    b.HasIndex("AnswerPropositionId");

                    b.HasIndex("SubjectId");

                    b.ToTable("QuestionAnswer");
                });

            modelBuilder.Entity("ReVision.Model.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ReVision.Model.Proposition", b =>
                {
                    b.HasOne("ReVision.Model.QAModel", null)
                        .WithMany("FalsePropositions")
                        .HasForeignKey("QAModelId");
                });

            modelBuilder.Entity("ReVision.Model.QAModel", b =>
                {
                    b.HasOne("ReVision.Model.Proposition", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerPropositionId");

                    b.HasOne("ReVision.Model.Subject", null)
                        .WithMany("Qas")
                        .HasForeignKey("SubjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
